import os
import io
import pathlib
import pypandoc

rel_base_path = "win32/desktop-src/"
rel_spec_path = "spec/"

# List of Markdown files
md_files = [
    "direct3dhlsl/dx-graphics-hlsl-intrinsic-functions.md"
]
a = [
    "direct3dhlsl/abort.md",
    "direct3dhlsl/dx-graphics-hlsl-abs.md",
    "direct3dhlsl/dx-graphics-hlsl-acos.md",
    "direct3dhlsl/dx-graphics-hlsl-all.md",
    "direct3dhlsl/allmemorybarrier.md",
    "direct3dhlsl/allmemorybarrierwithgroupsync.md",
    "direct3dhlsl/dx-graphics-hlsl-any.md",
    "direct3dhlsl/asdouble.md",
    "direct3dhlsl/dx-graphics-hlsl-asfloat.md",
    "direct3dhlsl/dx-graphics-hlsl-asin.md",
    "direct3dhlsl/dx-graphics-hlsl-asint.md",
    "direct3dhlsl/asuint.md",
    "direct3dhlsl/dx-graphics-hlsl-asuint.md",
    "direct3dhlsl/dx-graphics-hlsl-atan.md",
    "direct3dhlsl/dx-graphics-hlsl-atan2.md",
    "direct3dhlsl/dx-graphics-hlsl-ceil.md",
    "direct3dhlsl/dx-graphics-hlsl-clamp.md",
    "direct3dhlsl/dx-graphics-hlsl-clip.md",
    "direct3dhlsl/dx-graphics-hlsl-cos.md",
    "direct3dhlsl/dx-graphics-hlsl-cosh.md",
    "direct3dhlsl/countbits.md",
    "direct3dhlsl/dx-graphics-hlsl-cross.md",
    "direct3dhlsl/dx-graphics-hlsl-d3dcolortoubyte4.md",
    "direct3dhlsl/dx-graphics-hlsl-ddx.md",
    "direct3dhlsl/ddx-coarse.md",
    "direct3dhlsl/ddx-fine.md",
    "direct3dhlsl/dx-graphics-hlsl-ddy.md",
    "direct3dhlsl/ddy-coarse.md",
    "direct3dhlsl/ddy-fine.md",
    "direct3dhlsl/dx-graphics-hlsl-degrees.md",
    "direct3dhlsl/dx-graphics-hlsl-determinant.md",
    "direct3dhlsl/devicememorybarrier.md",
    "direct3dhlsl/devicememorybarrierwithgroupsync.md",
    "direct3dhlsl/dx-graphics-hlsl-distance.md",
    "direct3dhlsl/dx-graphics-hlsl-dot.md",
    "direct3dhlsl/dst.md",
    "direct3dhlsl/errorf.md",
    "direct3dhlsl/evaluateattributecentroid.md",
    "direct3dhlsl/evaluateattributeatsample.md",
    "direct3dhlsl/evaluateattributesnapped.md",
    "direct3dhlsl/dx-graphics-hlsl-exp.md",
    "direct3dhlsl/dx-graphics-hlsl-exp2.md",
    "direct3dhlsl/f16tof32.md",
    "direct3dhlsl/f32tof16.md",
    "direct3dhlsl/dx-graphics-hlsl-faceforward.md",
    "direct3dhlsl/firstbithigh.md",
    "direct3dhlsl/firstbitlow.md",
    "direct3dhlsl/dx-graphics-hlsl-floor.md",
    "direct3dhlsl/dx-graphics-hlsl-fma.md",
    "direct3dhlsl/dx-graphics-hlsl-fmod.md",
    "direct3dhlsl/dx-graphics-hlsl-frac.md",
    "direct3dhlsl/dx-graphics-hlsl-frexp.md",
    "direct3dhlsl/dx-graphics-hlsl-fwidth.md",
    "direct3dhlsl/dx-graphics-hlsl-getrendertargetsamplecount.md",
    "direct3dhlsl/dx-graphics-hlsl-getrendertargetsampleposition.md",
    "direct3dhlsl/groupmemorybarrier.md",
    "direct3dhlsl/groupmemorybarrierwithgroupsync.md",
    "direct3dhlsl/interlockedadd.md",
    "direct3dhlsl/interlockedand.md",
    "direct3dhlsl/interlockedcompareexchange.md",
    "direct3dhlsl/interlockedcomparestore.md",
    "direct3dhlsl/interlockedexchange.md",
    "direct3dhlsl/interlockedmax.md",
    "direct3dhlsl/interlockedmin.md",
    "direct3dhlsl/interlockedor.md",
    "direct3dhlsl/interlockedxor.md",
    "direct3dhlsl/dx-graphics-hlsl-isfinite.md",
    "direct3dhlsl/dx-graphics-hlsl-isinf.md",
    "direct3dhlsl/dx-graphics-hlsl-isnan.md",
    "direct3dhlsl/dx-graphics-hlsl-ldexp.md",
    "direct3dhlsl/dx-graphics-hlsl-length.md",
    "direct3dhlsl/dx-graphics-hlsl-lerp.md",
    "direct3dhlsl/dx-graphics-hlsl-lit.md",
    "direct3dhlsl/dx-graphics-hlsl-log.md",
    "direct3dhlsl/dx-graphics-hlsl-log10.md",
    "direct3dhlsl/dx-graphics-hlsl-log2.md",
    "direct3dhlsl/mad.md",
    "direct3dhlsl/dx-graphics-hlsl-max.md",
    "direct3dhlsl/dx-graphics-hlsl-min.md",
    "direct3dhlsl/dx-graphics-hlsl-modf.md",
    "direct3dhlsl/dx-graphics-hlsl-msad4.md",
    "direct3dhlsl/dx-graphics-hlsl-mul.md",
    "direct3dhlsl/dx-graphics-hlsl-noise.md",
    "direct3dhlsl/dx-graphics-hlsl-normalize.md",
    "direct3dhlsl/dx-graphics-hlsl-pow.md",
    "direct3dhlsl/printf.md",
    "direct3dhlsl/process2dquadtessfactorsavg.md",
    "direct3dhlsl/process2dquadtessfactorsmax.md",
    "direct3dhlsl/process2dquadtessfactorsmin.md",
    "direct3dhlsl/processisolinetessfactors.md",
    "direct3dhlsl/processquadtessfactorsavg.md",
    "direct3dhlsl/processquadtessfactorsmax.md",
    "direct3dhlsl/processquadtessfactorsmin.md",
    "direct3dhlsl/processtritessfactorsavg.md",
    "direct3dhlsl/processtritessfactorsmax.md",
    "direct3dhlsl/processtritessfactorsmin.md",
    "direct3dhlsl/dx-graphics-hlsl-radians.md",
    "direct3dhlsl/rcp.md",
    "direct3dhlsl/dx-graphics-hlsl-reflect.md",
    "direct3dhlsl/dx-graphics-hlsl-refract.md",
    "direct3dhlsl/reversebits.md",
    "direct3dhlsl/dx-graphics-hlsl-round.md",
    "direct3dhlsl/dx-graphics-hlsl-rsqrt.md",
    "direct3dhlsl/dx-graphics-hlsl-saturate.md",
    "direct3dhlsl/dx-graphics-hlsl-sign.md",
    "direct3dhlsl/dx-graphics-hlsl-sin.md",
    "direct3dhlsl/dx-graphics-hlsl-sincos.md",
    "direct3dhlsl/dx-graphics-hlsl-sinh.md",
    "direct3dhlsl/dx-graphics-hlsl-smoothstep.md",
    "direct3dhlsl/dx-graphics-hlsl-sqrt.md",
    "direct3dhlsl/dx-graphics-hlsl-step.md",
    "direct3dhlsl/dx-graphics-hlsl-tan.md",
    "direct3dhlsl/dx-graphics-hlsl-tanh.md",
    "direct3dhlsl/dx-graphics-hlsl-tex1d.md",
    "direct3dhlsl/dx-graphics-hlsl-tex1d-s-t-ddx-ddy.md",
    "direct3dhlsl/dx-graphics-hlsl-tex1dbias.md",
    "direct3dhlsl/dx-graphics-hlsl-tex1dgrad.md",
    "direct3dhlsl/dx-graphics-hlsl-tex1dlod.md",
    "direct3dhlsl/dx-graphics-hlsl-tex1dproj.md",
    "direct3dhlsl/dx-graphics-hlsl-tex2d.md",
    "direct3dhlsl/dx-graphics-hlsl-tex2d-s-t-ddx-ddy.md",
    "direct3dhlsl/dx-graphics-hlsl-tex2dbias.md",
    "direct3dhlsl/dx-graphics-hlsl-tex2dgrad.md",
    "direct3dhlsl/dx-graphics-hlsl-tex2dlod.md",
    "direct3dhlsl/dx-graphics-hlsl-tex2dproj.md",
    "direct3dhlsl/dx-graphics-hlsl-tex3d.md",
    "direct3dhlsl/dx-graphics-hlsl-tex3d-s-t-ddx-ddy.md",
    "direct3dhlsl/dx-graphics-hlsl-tex3dbias.md",
    "direct3dhlsl/dx-graphics-hlsl-tex3dgrad.md",
    "direct3dhlsl/dx-graphics-hlsl-tex3dlod.md",
    "direct3dhlsl/dx-graphics-hlsl-tex3dproj.md",
    "direct3dhlsl/dx-graphics-hlsl-texcube.md",
    "direct3dhlsl/dx-graphics-hlsl-texcube-s-t-ddx-ddy.md",
    "direct3dhlsl/dx-graphics-hlsl-texcubebias.md",
    "direct3dhlsl/dx-graphics-hlsl-texcubegrad.md",
    "direct3dhlsl/dx-graphics-hlsl-texcubelod.md",
    "direct3dhlsl/dx-graphics-hlsl-texcubeproj.md",
    "direct3dhlsl/dx-graphics-hlsl-transpose.md",
    "direct3dhlsl/dx-graphics-hlsl-trunc.md",
    "direct3dhlsl/wavegetlanecount.md",
    "direct3dhlsl/wavegetlaneindex.md",
    "direct3dhlsl/waveisfirstlane.md",
    "direct3dhlsl/waveanytrue.md",
    "direct3dhlsl/wavealltrue.md",
    "direct3dhlsl/waveballot.md",
    "direct3dhlsl/wavereadlaneat.md",
    "direct3dhlsl/wavereadfirstlane.md",
    "direct3dhlsl/waveactiveallequal.md",
    "direct3dhlsl/waveallbitand.md",
    "direct3dhlsl/waveallbitor.md",
    "direct3dhlsl/waveallbitxor.md",
    "direct3dhlsl/waveactivecountbits.md",
    "direct3dhlsl/waveallmax.md",
    "direct3dhlsl/waveactivemin.md",
    "direct3dhlsl/waveallproduct.md",
    "direct3dhlsl/waveallsum.md",
    "direct3dhlsl/waveprefixcountbytes.md",
    "direct3dhlsl/waveprefixsum.md",
    "direct3dhlsl/waveprefixproduct.md",
    "direct3dhlsl/quadreadlaneat.md",
    "direct3dhlsl/quadreadacrossdiagonal.md",
    "direct3dhlsl/quadswapx.md",
    "direct3dhlsl/quadswapy.md",
    "direct3d12/traceray-function.md",
    "direct3d12/reporthit-function.md",
    "direct3d12/callshader-function.md",
    "direct3d12/ignorehit-function.md",
    "direct3d12/accepthitandendsearch-function.md",
    "direct3d12/dispatchraysindex.md",
    "direct3d12/dispatchraysdimensions.md",
    "direct3d12/worldrayorigin.md",
    "direct3d12/worldraydirection.md",
    "direct3d12/objectrayorigin.md",
    "direct3d12/objectraydirection.md",
    "direct3d12/raytmin.md",
    "direct3d12/raytcurrent.md",
    "direct3d12/primitiveindex.md",
    "direct3d12/instanceid.md",
    "direct3d12/instanceindex.md",
    "direct3d12/geometryindex.md",
    "direct3d12/hitkind.md",
    "direct3d12/rayflags.md",
    "direct3d12/objecttoworld3x4.md",
    "direct3d12/worldtoobject3x4.md",
    "direct3d12/objecttoworld4x3.md",
    "direct3d12/worldtoobject4x3.md",
    "direct3d12/setmeshoutputcounts.md"
]
spec_dir_path = os.path.join(pathlib.Path().resolve(), rel_spec_path);
os.makedirs(spec_dir_path, exist_ok=True)
os.makedirs(os.path.join(spec_dir_path,"direct3dhlsl"), exist_ok=True)
os.makedirs(os.path.join(spec_dir_path,"direct3d12"), exist_ok=True)
# Iterate through the list of Markdown files
for md_file in md_files:
    # Extract the file name without extension
    file_name = md_file.split(".md")[0]

    # Generate the LaTeX file name
    tex_file = file_name + ".tex"

    # Run pandoc command to convert Markdown to LaTeX
    # pandoc_command = [
    #    "pandoc",
    #    "--read=markdown",
    #    "--write=latex",
    #    f"--output={tex_file}",
    #    "--standalone",
    #    md_file
    # ]
    # Execute the pandoc command
    # subprocess.run(pandoc_command)

    full_md_filepath = os.path.join(pathlib.Path().resolve(),
                                    rel_base_path,
                                    md_file)
    full_spec_filepath = os.path.join(spec_dir_path,
                                      tex_file)
    
    if os.path.exists(full_md_filepath):
        output = pypandoc.convert_file(
            full_md_filepath,
            "latex",
            format="markdown",
            outputfile=full_spec_filepath)
        print(f"Converted {md_file} to {tex_file}")
